os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

build_script:
  - build.cmd

deploy:
  - provider: NuGet
    api_key:
      secure: 6IOnCr0vcNuRan0YWj7JRzsjZINxy7QuKAsg1HvdmYIOvTMV/ZbFyaRbL5X8OOmY
    artifact: /.*\.nupkg/
    on:
      branch: master
      
nuget:
  project_feed: true
  disable_publish_on_pr: true
  
artifacts:
  - path: '*.nupkg'
    name: Packages
